pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["adaptacion_de_un_proceso_2_5_1.htm","2.5.1 Adaptación de un proceso ","2.5.1 Adaptación de un proceso Top Previous Next Para realizar la adaptación de un proceso se debe hacer click derecho sobre el proceso adaptado c...",""],
["bienvenida.htm","1.1 Bienvenida","1.1 Bienvenida Top Previous Next La herramienta da soporte tecnológico al paradigma VRP para la definición de procesos ricos en variantes en el co...",""],
["creacion_de_dependencias_2_4.htm","2.4 Creación de dependencias ","2.4 Creación de dependencias Top Previous Next En este apartado se aprenderá a generar dependencias con los puntos de variación y las variantes. P...",""],
["creacion_de_puntos_de_variacio.htm","2.2 Creación de puntos de variación ","2.2 Creación de puntos de variación Top Previous Next Para la creación de un punto de variación lo primero que se debe hacer es crear un proceso e...",""],
["creacion_de_un_proceso_adaptad.htm","2.5 Creación de un proceso adaptado ","2.5 Creación de un proceso adaptado Top Previous Next Para crear un proceso adaptado se debe tener al menos una Variante para poder generar un pro...",""],
["creacion_de_una_linea_de_proce.htm","2.1 Creación de una línea de procesos","2.1 Creación de una línea de procesos Top Previous Next Para crear una Línea de proceso deberemos situarnos sobre el paquete de Process Lines, y c...",""],
["creacion_de_variantes_2_3.htm","2.3 Creación de variantes ","2.3 Creación de variantes Top Previous Next Para la creación de variantes se siguen los mismos pasos que se han seguido dentro de la creación de p...",""],
["generacion_de_reportes.htm","2.6.1 Generación de reportes","2.6.1 Generación de reportes Top Previous vEPFC tiene una funcionalidad extra para poder generar reportes en .pdf actualmente. El reporte que se p...",""],
["introduccion.htm","1 Introducción","1 Introducción Top Next ",""],
["manual_de_usuario.htm","2 Manual de usuario","2 Manual de usuario Top Previous Next ",""],
["miscelanea.htm","2.6 Miscelánea","2.6 Miscelánea Top Previous Next Enter topic text here. ",""],
["vepfc_ftsearch.htm","Variant Eclipse Process Framework Composer","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""]];
